import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FormularioLogin from '../componentes/Pagina-login/formulario/formulario'
import { useContext } from 'react'
import { AuthContext } from '../context/Auth.js'

export default function Home() {
  const { singUserColaborador, signUserLider } = useContext(AuthContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <FormularioLogin singUserColaborador={singUserColaborador} signUserLider={signUserLider} />
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}



